version: "3.7"

services:
  web-server:
    image: nginx:1.17.10-alpine
    container_name: web-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/
    ports:
      - 80:80
    networks:
      nuxt-network:
    depends_on:
      - nuxt-app
    restart: unless-stopped

  nuxt-app:
    build: ./
    container_name: nuxt-app
    restart: always
    ports:
      - "3000:3000"
    command: "npm run start"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge